### ISSUE TITLE
Rewinding state after stop/stopChild

### ISSUE THREAD

**Issue by xjki** [radianttap/Coordinator#10]
I wonder if `Coordinator.stop()` & `Coordinator.stopChild()` should rewind `rootViewController.parentCoordinator` value. 

Currently `rootViewController.parentCoordinator = nil` after `Coordinator.stop()` but it can be that it had different value before `Coordinator.start()` / `Coordinator.startChild()` was called.

E.g. 
`AppCoordinator` initialized with `rootViewController = AppNavController` 
and `ChildCoordinator`initialized with the same `rootViewController = AppNavController `
then after `ChildCoordinator.didFinish `
`AppNavController.parentCoordinator` will be nil instead of `AppCoordinator`.

Of course it can be mitigated with overriding 

```
    override func stopChild(coordinator: Coordinating, completion: @escaping () -> Void) {
        super.stopChild(coordinator: coordinator) {
            self.rootViewController.parentCoordinator = self
        }
    }
```

Maybe capturing `rootViewController.parentCoordinator` value in `start()` / `startChild()` and setting it back in `stop()` / `stopChild() `would be more reliable/foolproof option?

**Comment by radianttap** [comment]
I have noticed the need for this to happen and I did some initial attempts to handle this in two ongoing projects. I'll comeback when I get more concrete results.

**Comment by xjki** [comment]
While it is not as clean as I would like I settled with this:
```
    public func stopChild(coordinator: Coordinating, completion: @escaping () -> Void = {}) {
        let childCoordinator = coordinator as? Coordinator
        let shouldRestoreRootViewControllerParentCoordinator = (childCoordinator != nil) && (rootViewController === childCoordinator?.rootViewController)
        coordinator.parent = nil
        coordinator.stop { [unowned self] in
            self.childCoordinators.removeValue(forKey: coordinator.identifier)
            if shouldRestoreRootViewControllerParentCoordinator {
                self.rootViewController.parentCoordinator = self
            }
            completion()
        }
    }
```

**Comment by radianttap** [comment]
`childCoordinators` is Dictionary. It simply keeps whatever is already created in memory. So it's not fit to also keep the information what Coordinator should be restored as owner of root NC.

A simple singular property would not do, since that breaks down after creating and loading 3rd child and stopping both the 2nd and 3rd.

Maybe add another property like `orderedCoordinators: [Coordinating]`..? 
Note that if you have PopupCoordinator with VCs that are not displayed on the root NC, then it should not be added to that array. But why would any Coordinator know that something it creates will be a popup or not. 

Ugh...I can't seem to lock-on the solution that would work in general case.

**Comment by radianttap** [comment]
I went again through your solution and discussion and it seems to me there is no global answer here. 

It's not enough to just restore `parentCoordinator` on the `rootViewController` - you also need to make sure `viewControllers` from that previous/new Coordinator are also installed on the rootVC. Which means different things depending what rootVC is.

Most likely solution here is to find one on case by case basis. At least I don't see how the library itself can reason this out. Parent Coordinator should know when stopChild or coordinatorDidFinish happen and it should do the correct case for each specific UI scenario.
