### ISSUE TITLE
Track `popViewController` when user taps Back bar button on iOS >= 10

### ISSUE THREAD

**Issue by psi-gh** [radianttap/Coordinator#11]
In current implementation of this library on iOS >= 10 in ```NavigationCoordinator``` class this function
```	func willShowController(_ viewController: UIViewController, fromViewController: UIViewController?)```

is never called because 
```navigationController.transitionCoordinator?.notifyWhenInteractionChanges```
only works for pop gesture. It leads to inconsistent ```NavigationCoordinator```'s state because ```self.viewControllers``` array is never cleared and never synched with VC hierarchy.

**Comment by psi-gh** [comment]
And probably there is issues with pop gesture navigation on iOS 9. Including issues when interaction is cancelled or paused/resumed

**Comment by psi-gh** [comment]
I'm testing now such modification of method on iOS10. Seems working with both back button and pop gesture. Also i will omit ios9 support at all.
```
	public func navigationController(_ navigationController: UINavigationController, willShow viewController: UIViewController, animated: Bool) {
		if #available(iOS 10.0, *) {
            if navigationController.transitionCoordinator?.isInteractive == false {
                let fromViewController = navigationController.transitionCoordinator?.viewController(forKey: .from)
                self.willShowController(viewController, fromViewController: fromViewController)
            } else {
                navigationController.transitionCoordinator?.notifyWhenInteractionChanges {
                    [unowned self] context in
                    guard !context.isInteractive else { return }
                    guard !context.isCancelled else { return }
                    let fromViewController = context.viewController(forKey: .from)
                    self.willShowController(viewController, fromViewController: fromViewController)
                }
            }
		} else {
			//    get the FROM coordinator in the NC transition
			let fromViewController = navigationController.transitionCoordinator?.viewController(forKey: .from)
			self.willShowController(viewController, fromViewController: fromViewController)
		}
	}
```

**Comment by xieweizhi** [comment]
@psi-gh , Hey, I think this is fixed in #8

**Comment by psi-gh** [comment]
@xieweizhi Hi! This commit already merged into master, so this bug presents in current version of repo.

**Comment by radianttap** [comment]
This needs to be tested in actual live projects, but for now it's in the [develop branch](https://github.com/radianttap/Coordinator/commit/691ed00890fd894eba4a41dbefda5b07f5c0d7e4)

**Comment by radianttap** [comment]
This patch survived for a week in a large live app, thus I hope it's fine. :)
