### ISSUE TITLE
Support  Carthage

### ISSUE THREAD

**Issue by MarcSteven** [radianttap/Coordinator#13]
I think Carthage is a great tool to manage dependency   ,so most developer like to use it ,So Pls think about whether it should support Carthage?

**Comment by radianttap** [comment]
I personally don't use Carthage, although I plan to try it. 
Can you fork the project, create the required changes in a separate branch and post a pull request..?

**Comment by MarcSteven** [comment]
Ok，I will @radianttap

**Comment by mxcl** [comment]
There's an `xcodeproj` in the Example directory, which presumably can be adapted to vend a shared framework and build the demo when opened. Thus Carthage will find the framework and ignore the demo. It will need to be moved to the root directory, and renamed.

**Comment by radianttap** [comment]
I added a `carthage` branch with lots of changes to support this. Mainly to re-organize files around so I can share example core files between CocoaPods example and Carthage example.

Naming should be correct. 
I also updated the project versioning so it does not all say 1.0 and 1. :)

Few more stuff to do before merging into master:

- need to check is iOS framework working properly in 3rd party project
- need to create separate tvOS framework (right?)

**Comment by mxcl** [comment]
> need to create separate tvOS framework (right?)

Well, strictly you don’t, we use this trick for PromiseKit:

https://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

If you choose to have one target per platform its important to make sure they result in the same module name.

**Comment by mxcl** [comment]
I had a quick look, it looks good to me! You could make the following changes:

* Unshare the “Example” scheme
* Check the app-extension API only check box (unless you cannot)

**Comment by radianttap** [comment]
> > need to create separate tvOS framework (right?)
> 
> Well, strictly you don’t, we use this trick for PromiseKit:
> 
> https://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/
> 
> If you choose to have one target per platform its important to make sure they result in the same module name.

Oooh, this is **very** welcome, even with warnings and caveats. Many thanks for the info, will finish this as soon as day work allows.

**Comment by radianttap** [comment]
I believe this should be fine.
I'll wait few days before merging.

@MarcSteven please do try, if you have an existing project using Carthage.
