### ISSUE TITLE
Non-animated pop is not detected in NavigationCoordinator

### ISSUE THREAD

**Issue by krin-san** [radianttap/Coordinator#19]
I've noticed one critical issue with `NavigationCoordinator`: `handlePopBack` is not being called when `popViewController(animated: false)`. In this case `navigationController.transitionCoordinator` will be `nil` and pop detection mechanism will not work properly. As the result, we'll get a different `viewControllers` arrays on coordinator and navigation controller.

p.s.: Default pop animation was disabled to apply a custom `CATransition` animation.

I see only one *good* way to solve that by handling the case when `fromViewController == nil` separately. Whenever `viewController` which is being shown already exists in `viewControllers` array, that shall be treated as a pop event.

Feel free to propose a better solution. Meanwhile I will implement this one and test in my app.

**Comment by krin-san** [comment]
Hmm... I know, this breaks the pattern completely, but the same issue arise when `navigationController.popToViewController(_:animated:)` is called animated. `NavigationCoordinator` removes just the last controller from its `viewController` array. I will address this issue in my fix as well.

**Comment by radianttap** [comment]
Thank you very much for the fix and especially for the tests.

It's funny though – since I started using Coordinators 2+ years ago, I never had reason to pop more than one ViewController :). I generally just used `root(vc)` and `show(vc)` methods on the `NavigationCoordinator`, plus `handlePopBack` which takes care of customer tapping the back button.

**Comment by radianttap** [comment]
I am a bit puzzled by some of the checks you added. I'll try to add some comments into the code to explain my thinking.

**Comment by radianttap** [comment]
This really got me thinking...do I even need to care about fromViewController in this method..?
[Coded changes](https://github.com/radianttap/Coordinator/commit/09b040f68f8599d37b24ddebc60a6d4bb3f052a1) in the pop-detect branch.


Update: resolved trough #22, merged into master

**Comment by krin-san** [comment]
I just tried to integrate your library step-by-step into existing app, allowing some controllers to manage navigation stack outside coordinator – that's when I noticed the issue with `popViewController(animated: false)`. Revealed other cases while trying to "break" it even more :)
