### ISSUE TITLE
Bloated Namespace

### ISSUE THREAD

**Issue by TekEffekt** [radianttap/Coordinator#23]
Hello.

At scale, would this not bloat the namespace for all UIResponders, since each has been extended with all of these functions? It could one day become hundreds of public functions on each UIView, UIViewController, and Coordinator.

**Comment by radianttap** [comment]
In my practice, it's dozens, not hundreds.

In the largest project where I do this — (120+ View Controllers, 20+ middleware objects and 8 Coordinators) — I have ~70 coordinatingResponder methods. Where Accounting only takes up about 25, the rest are mostly 5-10
