### ISSUE TITLE
Unable to compile CoordinatorExample.xcodeproj

### ISSUE THREAD

**Issue by JeanAzzopardi** [radianttap/Coordinator#24]
I am getting this error message when I compile with carthage:

`Reason: Project /Carthage/Checkouts/Coordinator/Example/CoordinatorExample.xcodeproj cannot be opened because it is missing its project.pbxproj file.`

Indeed the project.pbxproj file is not there

**Comment by radianttap** [comment]
That's a wrong path, there's a Coordinator.xcodeproj in the root. 🤨 
I'll have to find time to dig into internal workings of the Carthage and how it selects the project/scheme. For now, I'll just remove those superfluous projects and leave the main one.

**Comment by JeanAzzopardi** [comment]
Thanks for the prompt fix <3
