### ISSUE TITLE
[Refactor] :Make code clean

### ISSUE THREAD

**Issue by MarcSteven** [radianttap/Coordinator#25]
I think the code is not clean ,so plan to refactor the code

**Comment by MarcSteven** [comment]
#26 #27 did this job ,so closed the issue

**Comment by radianttap** [comment]
I'm not sure what exactly is gained by splitting the file into two...

**Comment by MarcSteven** [comment]
@radianttap I think we should conform to SR ,so I refactor this code ,because they are two parts of extension -One is UIViewController and the another one is UIResponder....It's a small change to improve the code.So do you think about importing the framework to make code style well [SwiftLint](https://github.com/realm/SwiftLint).
How do you think about it ???

**Comment by radianttap** [comment]
I strive to follow SR but don't subscribe to it at all costs. Single responsibilty in this case would have been implementation of coordinatingResponder, not simply writing the extensions per type. But I do see your point as valid.

On the topic of SwiftLint, I don't care much about that. I have my habits how I write code, what code I find readable and thus don't care much about anyone's specific style guide :)

**Comment by MarcSteven** [comment]
Ok @radianttap I won't spend time on this issue ,thank for your info.......

**Comment by radianttap** [comment]
Hm, not sure was it clear what I meant: I will accept and merge the pull requests to split the extension into two files. The "don't care much" part was specifically about SwiftLint.
