### ISSUE TITLE
How to compile and run the example app?

### ISSUE THREAD

**Issue by kevinrenskers** [radianttap/Coordinator#28]
I've opened `Coordinator.xcodeproj` but am unable to compile the project: "No such module 'TinyConstraints'" (and the same for the other external dependencies).

I noticed that there are 4 frameworks listed under the Frameworks map in the project navigator, but they reference non-existing frameworks. For example `Carthage/Build/iOS/TinyConstraints.framework`, which is not part of the repo. So is there some step missing in the readme? Do I need to do something with Carthage or something?

**Comment by radianttap** [comment]
Yes, `carthage update --no-build`  & `carthage build --platform iOS` should be run.

Note: I'm planning to retire the example project here as I'm building a separate repo as example for the entire architecture approach.
