### ISSUE TITLE
Tutorial request - A sample xcproject?

### ISSUE THREAD

**Issue by hey-amo** [radianttap/Coordinator#31]
Hi there

I am a bit stumped as to how to use ApplicationCoordinator or what it should inherit from.  In the readme the ApplicationCoordinator is suffixed with three dots ... so I'm not sure what it is subclassing.

I am wondering, is there any chance of a sample xcproject that perhaps covers a few cases?

IE:
* Two journeys (1. A root Main menu and  2. Master -> Detail page)?
* How to hide back button/navigation altogether from one journey, but not the other?
* If two journeys have different storyboards altogether?

With thanks

**Comment by radianttap** [comment]
Take a look at [Spotifier demo app](https://github.com/radianttap/Spotifier). It's a bit old now, but still good regarding how to use Coordinators.
