### ISSUE TITLE
Can't use Struct as params in UIResponder's method

### ISSUE THREAD

**Issue by calvingit** [radianttap/Coordinator#35]
Something not so good. The params of method extended from UIResponder have to be NSObject.
Well, I can't use struct as model type now.

```swift
public struct User {
    let name = ""
}

public extension UIResponder {
    // Error
    // Xcode tips: Method cannot be marked @objc because the type of the parameter cannot be represented in Objective-C
    @objc func navigate(_ user: User) {
        coordinatingResponder?.navigate(user)
    }

    // OK
    @objc func navigateOC(_ list: [String]) {
        coordinatingResponder?.navigateOC(list)
    }
}
```

**Comment by radianttap** [comment]
Yes, Objective-C world has nothing but classes and integers.

You can workaround this by boxing the struct (or anything non-ObjC) into a class and passing that. See an example near the end of [my original article on coordinators](https://aplus.rs/2017/mvc-c-injecting-coordinator-pattern-in-uikit/), look for `ColorBox`
