### ISSUE TITLE
Bubbling events in the responder chain

### ISSUE THREAD

**Issue by mjjimenez** [radianttap/Coordinator#5]
Hi, I just wanted to ask if you're open to changing how actions are passed through the responder chain to the coordinator.

Currently, UIResponder is extended to adopt all the methods needed to be called by the cells on their corresponding coordinator. My problem with this is that it means all subclasses of UIResponder are now also able to call these methods even though they are unrelated to their own responsibilities.

I got some inspiration from this article ( https://blog.veloxdb.com/2016/05/12/bubbling-events-using-uiresponder-in-swift/ ) and was thinking if it could also be applied in this project.

For example, from the sample project, cart events could be defined in a protocol:

```
protocol CartEventHandler {
    func cartBuyNow(_ product: Product, sender: Any?)
    func cartAdd(product: Product, color: ColorBox, sender: Any?, completion: (Bool) -> Void)
    func cartToggle(sender: Any?)
}
```

and the `AppCoordinator` would then adopt protocol like so:

```
extension AppCoordinator: CartEventHandler {
    
    func cartBuyNow(_ product: Product, sender: Any?) {
         ...
    }
    
    func cartAdd(product: Product, color: ColorBox, sender: Any?, completion: (Bool) -> Void) {
        ...
    }
    
    func cartToggle(sender: Any?) {
        ...
    }
}
```

The UIResponder could have an additional function that walks the coordinating responder chain to find a matching responder that adopts this protocol.

```
public extension UIResponder {
	public var coordinatingResponder: UIResponder? {
		return next
	}
    
    func nextActionableResponder<T>() -> T? {
        guard let responder = self.coordinatingResponder else {
            return nil
        }
        
        return (responder as? T) ?? responder.nextActionableResponder()
    }
}
```

The `PromoCell` would then invoke the buy now method on the coordinator via the `nextActionableResponder()` function.

```
fileprivate extension PromoCell {
	@IBAction func didTapBuyNow(_ sender: UIButton) {
		guard let product = product else { return }

                (nextActionableResponder() as CartEventHandler?)?.cartBuyNow(product, sender: self)
	}
}
```

Thanks again for making the library. This is probably the best open source example of Coordinators I can currently find.

**Comment by radianttap** [comment]
I am open to all suggestions but I lack the time to properly think this through. Bunch of client work plus two conferences in September. One of those is NSSpain where I will be presenting this very topic thus I may be coming back to this.

Many thanks for taking the time to propose these changes, I will go through them, as well as pull requests

**Comment by mjjimenez** [comment]
No worries. Good luck with the event in Spain.

**Comment by radianttap** [comment]
I was thinking about this while making the latest update.

It adds a bit of boilerplate at each calling site which goes against the simplicity I was striving for. Main idea for this was to replicate the magic of `show(vc...)`, not necessarily to have the cleanest Swift. 

I think that by simply using prefix in the method name (like _cart_) it will be good enough to clue-in the developer where the method belongs.

**Comment by mjjimenez** [comment]
Fair enough. Casting to the event handler does kind of look ugly.
