### ISSUE TITLE
UITabBarController as Root or Child Coordinator

### ISSUE THREAD

**Issue by sirvon** [radianttap/Coordinator#9]
Thanks for sharing this design.
I am very keen on learning your implementation of the pattern.

I can't say for sure bc I haven't experienced the flow in use, but it seems this style is quite unique and understandable.

Working my way through the code, it seems like this style can be mixed and match with other architectural styles.

Can show me some sample code or some thoughts on how to incorporate UITabBarController as the root coordinator or as one of the child coordinators?

thanks!

**Comment by radianttap** [comment]
In general, I tend to avoid tab bar controllers and aim to flatten my controller hierarchy. 

Quick thoughts:

1. ApplicationCoordinator's root VC will be UITabBarController
2. Each tab will have its own Coordinator, most likely NavigationCoordinator with root VC = UINavigationController
3. Then business as usual inside the Coordinators

**Comment by sirvon** [comment]
> In general, I tend to avoid tab bar controllers and aim to flatten my controller hierarchy.

Can you explain what you mean by, "flatten my controller hierarchy".

Can you speak more on your methods to accomplish such?
it it pretty much, just avoid UITabBarController altogether....

Thank You.

**Comment by radianttap** [comment]
Very late to respond, but I finally had some time to [write a proper post](http://aplus.rs/2018/tabbarcontroller-using-coordinators/), since explaining this requires a bit more text. @sirvon I hope it's useful.

**Comment by koenvanderdrift** [comment]
Also a late response, this is how I use this in my app. AppCoordinator still have a `UINavigationController` as the rootViewController, in case eg a login screen is needed. It then creates a TabBarCoordinator using that rootViewController. The TabBarCoordinator then sets up the UITabBarController - in my case from a StoryBoard: 

 ```
override func start(with completion: @escaping () -> Void = {}) {
        super.start(with: completion)
        
        let tabBarController = UITabBarController.instantiate(fromStoryboardNamed: "Main")
        
        rootViewController.isNavigationBarHidden = true
        root(tabBarController)

        for vc in tabBarController.children {
     // set up the tabs a childCoordinators
      }
}
```
